### ISSUE TITLE
When enter is clicked two times in a row, new chat is created and it is stuck in the infinity loop

### ISSUE THREAD

**Issue by rjambrecic** [airtai/fastagency#450] opened 2024-06-28 07:24 UTC
![Image](https://github.com/airtai/fastagency/assets/32619626/917d512f-9dde-4dd3-ba9e-34a36059c01e)

**Comment by harishmohanraj** [comment] 2024-07-01 05:35
Duplicate of https://github.com/airtai/fastagency-wasp-app-template/issues/41

**Closed by harishmohanraj** 2024-07-01 05:35 UTC
Labels: duplicate
